document.querySelector('.menu-hamburger').onclick=function(e){
   e.preventDefault();
   document.querySelector('.navigation-header').classList.toggle('menu-smart');
   document.querySelector('.menu-hamburger').classList.toggle('menu-smart');
   e.onblur=function(){
   document.querySelector('.navigation-header').classList.remove('menu-smart');
   document.querySelector('.menu-hamburger').classList.remove('menu-smart');
   };
};
